ALTER TYPE "AddonType" ADD VALUE IF NOT EXISTS 'MAKEUP_BLISS_TEAM';
ALTER TYPE "AddonType" ADD VALUE IF NOT EXISTS 'ASSIST_MU_PARTY';
ALTER TYPE "AddonType" ADD VALUE IF NOT EXISTS 'ASSIST_MU_ENGAGEMENT';
ALTER TYPE "AddonType" ADD VALUE IF NOT EXISTS 'ASSIST_MU_WEDDING';
ALTER TYPE "AddonType" ADD VALUE IF NOT EXISTS 'ASSIST_MU_CLASS';

ALTER TABLE "EmployeeAddon" ADD COLUMN IF NOT EXISTS "note" TEXT;
